# Generated by Django 5.0 on 2025-10-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200, verbose_name='Movie name')),
                ('movie_description', models.TextField(blank=True, verbose_name='Movie description')),
                ('reason', models.TextField(verbose_name='Reason for petition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Petition',
                'verbose_name_plural': 'Petitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
